title: 'GITHUB EN EL AULA'
subtitle: 'Un Curso OCW de la ULL'
theme: jekyll-theme-midnight
light: true
description: 'Un Curso OCW de la ULL'
acronym: GHA
exclude: [ '_drafts/not-used/' ]
baseurl: '/ocw/pluginfile.php/19489/mod_resource/content/3/_site' # '/introduccion' '/ocw/pluginfile.php/19489/mod_resource/content/3/_site'
guia_docente: https://www.ull.es/apps/guias/guias/view_guide_course/2122/125771143
show_downloads: false
calendario_academico: https://www.ull.es/estudios-docencia/calendario-academico/
horarios_examenes: https://www.ull.es/grados/ingenieria-informatica/informacion-academica/horarios-y-calendario-examenes/
calendario_examenes: https://docs.google.com/document/d/1j5rJyULD1c42UV4o-g85puuPlbO-DNFmaobn_vnKgKw/edit#
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
google_plus: https://plus.google.com/u/1/communities/101901734024125937720
organization: 
  url: https://github.com/ULL-OCW-GITHUB-EDUCATION/
  name: ULL-OCW-GITHUB-EDUCATION
  master: https://github.com/ULL-OCW-GITHUB-EDUCATION/ULL-OCW-GITHUB-EDUCATION.github.io/tree/master/
apuntes_repo: https://github.com/ULL-OCW-GITHUB-EDUCATION/ULL-OCW-GITHUB-EDUCATION.github.io/
campus_virtual: https://campusvirtual.ull.es/ocw/course/view.php?id=136
calificador: https://campusdoctoradoyposgrado.ull.es/grade/report/grader/index.php?id=2020110589
tareas_en_el_campus: https://campusvirtual.ull.es/ingenieriaytecnologia/1920/mod/assign/index.php?id=201911070
profesor: https://campusvirtual.ull.es/ocw/mod/page/view.php?id=8937
profesor_github: crguezl
chat: https://chat.google.com
future: true
bull_permanente: https://puntoq.ull.es/permalink/f
covid_ull: https://campusvirtual.ull.es/doctoradoyposgrado/course/view.php?id=201913946
dsi:
  apuntes: https://ull-esit-dsi-1819.github.io/dsi-1819/
sytws:
  url: https://ull-mii-sytws-1920.github.io/
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: https://classroom.github.com/classrooms/109737506-ull-ocw-github-education 
  name: GHA
collections:
  tareas:
    output: true
temas:
# - title: 'Introducción al Desarrollo Colaborativo de Proyectos en la Nube'
#    url: '/tema0-introduccion/'
#    hover: 'introduccion'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con GitHub Education'
#  url: '/tema1-github-education'
#  hover: 'github-education'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con Google'
#  url: /tema2-google-app-scripts
#  hover: 'google-app-scripts' 
plugins:
  - jemoji

